version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - qdrant
    volumes:
      - ./backend:/app/backend

  frontend:
    build: ./frontend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  telegrambot:
    build: ./telegram_bot
    env_file:
      - ./.env
    depends_on:
      - backend

volumes:
  mongo_data:
  qdrant_data:
